### ISSUE TITLE
Implement the `GetHostname` action

### ISSUE THREAD

**Issue by larandaA** [google/rrg#4]
RRG should support the [`GetHostname`][hostname-action] action. It does not have any input arguments and should respond with [`DataBlob`][hostname-response].

[hostname-action]: https://github.com/google/grr/blob/f0c26b1e83e77a8f53f7b7aef706b418061682ae/grr/client/grr_response_client/client_actions/admin.py#L50-L57
[hostname-response]:
https://github.com/google/grr/blob/f0c26b1e83e77a8f53f7b7aef706b418061682ae/grr/proto/grr_response_proto/jobs.proto#L401-L423

**Comment by panhania** [comment]
Implemented in e2a62740fadbd318bd5be0e9d37d21cb009ebb1f as part of the [`get_sytem_metadata`](https://github.com/google/rrg/blob/e2a62740fadbd318bd5be0e9d37d21cb009ebb1f/proto/rrg/action/get_system_metadata.proto) action.
